version: '3'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5433"

  web_app:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - POSTGRES_HOST=db